package com.example.myloginapp.extentions

const val STRING_USER_EMAIL = "USER_EMAIL_CONSTANT"
const val STRING_WEB_URL_LOGIN_TOKEN = "https://development.user.api.brinesia.app/Dummy/verifyDummyByEmail2"
const val STRING_WEB_URL_REGISTER_EMAIL = "http://192.168.0.172:1000/user/insertUser"
const val STRING_WEB_URL_REQ_OTP = "http://192.168.0.172:1000/user/requestOTP"
const val STRING_WEB_URL_AUTH = "http://192.168.0.172:1000/user/authenticateUser"
const val STRING_CONTENT_TYPE = "Content-Type"
const val STRING_APPLICATION_TYPE = "application/json; charset=utf-8"
const val STRING_FORM_URL_ENCODED = "application/x-www-form-urlencoded"
const val STRING_POST = "POST"
const val STRING_GET = "GET"
const val STRING_EMAIL = "Email"
const val STRING_OTP = "OTP"
const val STRING_DATA = "Data"
const val INT_3_000_TIMEMILLS = 30000
const val TWITTER_CONSUMER_KEY = "VTMeeFKYCh9JM61Jtq496ggPU"
const val TWITTER_CONSUMER_KEY_SECRET = "fKOZgl0ZrKYaQNG2aL5gjAXYNsoTpwFHkbhPmjnJnaL6LsSTR6"
const val INSTAGRAM_CONSUMER_KEY = "479064287038844"
const val INSTAGRAM_CONSUMER_KEY_SECRET = "634611307afdd1433b3133d19d4e4f60"
const val INSTAGRAM_CLIENT_ID = "client_id"
const val INSTAGRAM_CLIENT_SECRET = "client_secret"
const val INSTAGRAM_GRANT_TYPE ="grant_type"
const val INSTAGRAM_REDIRECT_URI = "redirect_uri"
const val INSTAGRAM_CODE = "code"
const val INSTAGRAM_FIELDS = "fields"
const val INSTAGRAM_ACCESS_TOKEN = "access_token"
const val STRING_INSTAGRAM_FIELDS = "id,username"
const val STRING_INSTAGRAM_AUTH = "https://www.instagram.com/oauth/authorize?client_id=479064287038844&redirect_uri=https://github.com/itsannazzle&scope=user_profile,user_media&response_type=code"
const val STRING_INSTAGRAM_REDIRECT_URL = "https://github.com/itsannazzle"
const val STRING_INSTAGRAM_GRANT_TYPE = "authorization_code"
const val STRING_INSTAGRAM_AUTH_ACCESS_TOKEN_URL = "https://api.instagram.com/oauth/access_token"
const val STRING_INSTAGRAM_GRAPH_API = "https://graph.instagram.com/"